[package]
name = "icarust"
version = "0.1.0"
authors = ["Sam Pullman <sampullman@gmail.com>"]

[dependencies.ggez]
path = "../libraries/ggez/"
version = "0.3"

[dependencies.icarust-derive]
path = "../icarust-derive/"

[dependencies]
rand = "0.3"
nalgebra = "0.13"